from django.urls import path

from .views import (
    ContractCreateView,
    ContractDocumentDeleteView,
    ContractDocumentDetailView,
    ContractDocumentListView,
    ContractDocumentUploadView,
    ContractListView,
    ContractDetailView,
    ContractResponsibilityCreateView,
    ContractTaskCreateView,
    ContractTaskListView,
    ObligationCreateView,
    ObligationDeleteView,
    ObligationDetailView,
    ObligationListView,
    ObligationUpdateView,
    TaskDeleteView,
    TaskDetailView,
    TaskUpdateView,
    ContractDeleteView,
    ContractUpdateView,
)

urlpatterns = [
    path('contracts/create/', ContractCreateView.as_view(), name='contract-create'),
    path('contracts/', ContractListView.as_view(), name='list-contracts'),
    path('contracts/<int:contract_id>/', ContractDetailView.as_view(), name='contract-detail'),
    path('contracts/<int:contract_id>/documents/', ContractDocumentListView.as_view(), name='contract-document-list'),
    path('contracts/<int:contract_id>/documents/upload/', ContractDocumentUploadView.as_view(), name='contract-document-upload'),
    path('contracts/<int:contract_id>/documents/<int:document_id>/', ContractDocumentDetailView.as_view(), name='contract-document-detail'),
    path('contracts/<int:contract_id>/documents/<int:document_id>/delete/', ContractDocumentDeleteView.as_view(), name='contract-document-delete'),
    path('contracts/<int:contract_id>/delete/', ContractDeleteView.as_view(), name='contract-delete'),
    path('contracts/<int:contract_id>/update/', ContractUpdateView.as_view(), name='contract-update'),
    path('contracts/<int:contract_id>/responsibility/create/', ContractResponsibilityCreateView.as_view(), name='contract-responsibility-create'),
    path('contracts/<int:contract_id>/obligations/create/', ObligationCreateView.as_view(), name='obligation-create'),
    path('contracts/<int:contract_id>/obligations/', ObligationListView.as_view(), name='obligation-list'),
    path('contracts/<int:contract_id>/tasks/', ContractTaskListView.as_view(), name='contract-task-list'),
    path('contracts/<int:contract_id>/tasks/create/', ContractTaskCreateView.as_view(), name='contract-task-create'),
    path('tasks/<int:task_id>/', TaskDetailView.as_view(), name='task-detail'),
    path('tasks/<int:task_id>/update/', TaskUpdateView.as_view(), name='task-update'),
    path('tasks/<int:task_id>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('obligations/<int:obligation_id>/', ObligationDetailView.as_view(), name='obligation-detail'),
    path('obligations/<int:obligation_id>/update/', ObligationUpdateView.as_view(), name='obligation-update'),
    path('obligations/<int:obligation_id>/delete/', ObligationDeleteView.as_view(), name='obligation-delete'),
]
