# Generated by Django 6.0.3 on 2026-04-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auditauditlog_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditauditlog',
            name='changed_fields',
        ),
        migrations.RemoveField(
            model_name='auditauditlog',
            name='from_status',
        ),
        migrations.RemoveField(
            model_name='auditauditlog',
            name='performed_by_role',
        ),
        migrations.RemoveField(
            model_name='auditauditlog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='auditauditlog',
            name='to_status',
        ),
    ]
