# Generated by Django 6.0.3 on 2026-04-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_auditauditlog_changed_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditauditlog',
            name='obj_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
